### ISSUE TITLE
Update URL

### ISSUE THREAD

**Issue by cphillipsusu** [usu-access/Monday-Pope-Tech-Sync#1]
The URL we have used for this app in the past [from Monday](https://usu.monday.com/boards/4491264884/pulses/4491264915?term=pope&termColumns=XQAAAAJ9AAAAAAAAAABBKoKYORiNJSIWYuque7DOPSw0qvzM1ntS9YsZ5U6vuOvSR4JD-rpE0tLgZgO_otm3IlnzQrh2TFarjjkW3X9tckFNbPIkY2hDrUsPDa3MfGYJYKSOmeoekFbca7Q8Lcm__5K1gAA): 
http://applications.accessapps.link:3011/

Is no longer working,.

**Comment by cartersingle** [comment]
Moving this application to Coolify.

**Comment by cartersingle** [comment]
Updated on Monday Apps board
